apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  app_config: |-
    KEY1=value1
    KEY2=value2
    KEY3=value3
  connection_strings: |-
    DB_CONNECTION_STRING=postgres://user:password@db-hostname:5432/db-name
  other_data: |-
    URL=http://example.com
    USERNAME=admin
---
apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-container
      image: my-image
      envFrom:
        - configMapRef:
            name: my-config
      # your container spec goes here
